apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-frontend-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "user-frontend-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "user-frontend-chart.selectorLabels" . | nindent 4 }}
